routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'Shop\HomeController@index')->name('shop.home');



//ROTAS DO PAINEL DE CONTROLE (DASHBOARD)
Route::middleware(['auth', 'checkUserRole'])->group(function () {
        Route::get('dashboard/categoria/get', 'Dashboard\CategoriaController@getCategorias')->name('getCategorias');

        Route::get('dashboard/categoria/subcategorias', 'Dashboard\CategoriaController@getSubcategorias')->name('categoria.getSubcategorias');

        Route::resource('dashboard/categoria', 'Dashboard\CategoriaController')
        ->parameters([
                'categoria' => 'categoria',
        ])
        ->except('create', 'edit', 'show');


        Route::put('dashboard/subcategoria/{subcategoria}/categoria', 'Dashboard\SubcategoriaController@updateParent')->name('subcategoria.updateParent');

        Route::resource('dashboard/subcategoria', 'Dashboard\SubcategoriaController')
        ->parameters([
                'subcategoria' => 'subcategoria',
        ])
        ->only('store', 'destroy', 'update');
        

                
        //Rotas de atributos 
        Route::get('dashboard/atributos/get', 'Dashboard\AtributoController@getAtributos')->name('getAttributes');
        Route::resource('dashboard/atributo', 'Dashboard\AtributoController');

        Route::resource('dashboard/atributo.valores', 'Dashboard\ValorAtributoController')
                ->only('store', 'destroy')
                ->shallow();


        

        Route::PUT('dashboard/atributo/{atributo}/config', 'Dashboard\AtributoController@setConfig');

        

        //ATRIBUTOS DAS CONFIGURAÇÕES
        Route::POST('dashboard/produto/variation', 'Dashboard\ProdutoController@setVariation')->name('produto.setVariation');
        
        Route::POST('dashboard/produto/variation/generalAttribute', 'Dashboard\ProdutoController@setVariationsGeneralAttribute')->name('produto.setVariationsGeneralAttribute');

        Route::DELETE('dashboard/produto/variation', 'Dashboard\ProdutoController@destroyVariation')->name('produto.destroyVariation');

        // ATRIBUTOS DO PRODUTO
        Route::POST('dashboard/produto/generalAtribute', 'Dashboard\ProdutoController@setGeneralAttribute')->name('produto.setGeneralAttribute');
        
        Route::POST('dashboard/produto/simpleAttribute', 'Dashboard\ProdutoController@setSimpleAttribute')->name('produto.setSimpleAttribute');

        Route::PUT('dashboard/produto/multipleGeneralAttributes', 'Dashboard\ProdutoController@updateMultipleGeneralAttributes')->name('produto.updateMultipleGeneralAttributes');

        Route::PUT('dashboard/produto/{produto}/generalAttribute', 'Dashboard\ProdutoController@updateGeneralAttribute')->name('produto.updateGeneralAttribute');


        // FOTOS DO PRODUTO
        Route::POST('dashboard/produto/photos', 'Dashboard\ProdutoController@setPhotos')->name('produto.setPhotos');

        Route::POST('dashboard/produto/{produto}/photos/database', 'Dashboard\ProdutoController@setPhotosToDatabase')->name('produto.setPhotosToDatabase');

        Route::DELETE('dashboard/produto/photos', 'Dashboard\ProdutoController@destroyPhoto')->name('produto.destroyPhoto');
        
        Route::DELETE('dashboard/produto/photos/database', 'Dashboard\ProdutoController@destroyPhotoFromDatabase')->name('produto.destroyPhotoFromDatabase');


        // FOTO PRINCIPAL
        Route::POST('dashboard/produto/photos/main', 'Dashboard\ProdutoController@setMainPhoto')->name('produto.setMainPhoto');

        Route::PUT('dashboard/produto/{produto}/photos/main', 'Dashboard\ProdutoController@updateMainPhoto')->name('produto.updateMainPhoto');


       
        //CRUD Produtos
        Route::resource('dashboard/produto', 'Dashboard\ProdutoController')->except('edit');

});

//ROTAS DO SHOP
Route::get('shop/catalogo', 'Shop\ShopController')->name('shop.catalogo');

Route::get('shop/categorias', 'Shop\ShowCategorias')->name('shop.categorias');

Route::get('shop/produto/unavaliable', 'Shop\ShowProduto@unavaliable')->name('shop.produto.unavaliable');

Route::get('shop/produto/{produto}', 'Shop\ShowProduto@show')->name('shop.produto')->middleware('checkProductStatus');

Route::get('shop/produto/{produto}/avaliacoes', 'User\AvalController@index')->name('shop.produtos.avaliacoes');

Route::get('shop/produto/{produto}/variation', 'Dashboard\ProdutoController@getVariation')->name('produto.getVariation');


//ROTAS PERFIL DO USUÁRIO
Route::middleware(['auth'])->group(function () {
        //ROTAS PERFIL DE USUÁRIO
        Route::get('user/profile', 'UserController@show')->name('user.profile');

        Route::put('user/profile', 'UserController@update')->name('user.profile.update');

        Route::get('user/profile/edit', 'UserController@edit')->name('user.profile.edit');

        Route::resource('user/address', 'User\EnderecoUsuarioController')->except('show', 'index');

        Route::put('user/address/{address}/setMain', 'User\EnderecoUsuarioController@setMain')->name('address.setMain');

        Route::get('password/edit', 'UserController@editPassword')->middleware('password.confirm')->name('password.edit');

        Route::put('password', 'UserController@changePassword')->name('password.change');

        //ROTAS SACOLA DE PRODUTOS
        Route::get('user/bag', 'User\BagController@show')->name('user.bag')->middleware('checkUserBag');

        Route::get('user/bag/empty', 'User\BagController@empty')->name('user.bag.empty');

        Route::post('user/bag/produto', 'User\BagController@addProductToBag')->name('bag.produto.store');

        Route::delete('user/bag/produto/{produto}', 'User\BagController@removeProductFromBag')->name('bag.produto.delete');

        Route::put('user/bag/produto/{produto}/quantity', 'User\BagController@updateProductBagQuantity')->name('bag.produto.quantity');
        
        Route::post("user/bag/address", 'User\EnderecoUsuarioController@store')->name('bag.address.store');

        Route::put('user/bag/address/{address}', 'User\BagController@updateBagAddress')->name('bag.address.update');


        // ROTAS FAVORITOS
        Route::get('user/favorites', 'User\FavoritesController@index')->name('user.favorites');

        Route::POST('user/favorites/produto/{produto}', 'User\FavoritesController@addProductToFavorites')->name('favorites.produto.store');
        
        Route::DELETE('user/favorites/produto/{produto}', 'User\FavoritesController@removeProductFromFavorites')->name('favorites.produto.delete');


        // ROTAS DE PEDIDOS
        Route::get('user/orders', 'User\OrdersController@index')->name('user.orders');

        Route::get('user/orders/{order}', 'User\OrdersController@show')->name('user.orders.show');

        Route::put('shop/checkout/finish/shipping', 'Shop\Checkout@loadShippingValue')->name('shop.checkout.shipping');

        // ROTAS DE AVALIACOES
        Route::resource('user/orders.produto.avaliacao', 'User\AvalController')->except('index', 'show');

});

//ROTAS DE CHECKOUT
Route::middleware(['auth', 'checkProductsInBagStatus'])->group(function () {
        Route::get('shop/checkout/address', 'Shop\Checkout@address')->name('shop.checkout.address');

        Route::get('shop/checkout/personal-info', 'Shop\Checkout@personal_info')->name('shop.checkout.personal-info');

        Route::get('shop/checkout/finish', 'Shop\Checkout@finish')->middleware('checkUserInfo')->name('shop.checkout');

        Route::post('shop/checkout/finish', 'Shop\Checkout@order')->name('shop.checkout.order');
});

app/Http/Controllers/Dashboard/AtributoController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Categoria;
use App\TipoAtributo;
use App\ValorAtributo;
use App\Atributo;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class AtributoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('dashboard.atributo.atributo-index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //Recupera as categorias de produtos
        $categorias = Categoria::withCount('subcategorias')->get();
        
        //Recupera os tipos de atributos
        $tiposAtributos = TipoAtributo::all();
        return view('dashboard.atributo.atributo-create', ['categorias' => $categorias, 'tiposAtributos' => $tiposAtributos]);
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
   

    public function store(Request $request) {
        //Verifica se os valores dos campos, se preenchidos, são válidos
        $validated = $request->validate([
            'subcategoria' => 'required|integer|exists:App\Subcategoria,id',
            'nome' => [
                'required',
                'regex:/^[A-Za-záàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ ]+$/',
                'max:60',
            ],
            'tipoAtr' => 'required|integer|exists:App\TipoAtributo,id',   
            'is_configurable' => 'exclude_if:tipoAtr,3',
        ]);
        // VERIFICA SE O ATRIBUTO JÁ FOI CADASTRADO PARA A SUBCATEGORIA SELECIONADA
        if(Atributo::where('subcategorias_id', $validated['subcategoria'])->where('nome', $validated['nome'])->exists()) {
            return redirect()->back()->withErrors(['nome' => "O atributo dado já existe para a subcategoria selecionada"]);
        }

        //Gera uma instancia do atributo e define os valores das propriedades
        $atributo = new Atributo();
        $atributo->subcategorias_id = $validated['subcategoria'];
        $atributo->nome = $validated['nome'];
        $replaced = Str::snake($validated['nome']);
        $atributo->label = $replaced;
        $atributo->tipos_atributos_id =  $validated['tipoAtr'];
        $atributo->is_visible = $request->has('is_visible') ? 1 : 0;
        $atributo->is_required = $request->has('is_required') ? 1 : 0;
        $atributo->is_configurable = isset($validated['is_configurable']) ? 1 : 0;
        $atributo->save();

        //Redireciona a página de cadastro dos atributos
        return redirect()->route('atributo.show', [$atributo->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Atributo $atributo) {
        return view('dashboard.atributo.atributo-show', ['atributo' => $atributo]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Atributo $atributo)
    {
        $categorias = Categoria::withCount('subcategorias')->get();
        $tipos = TipoAtributo::all();

        //Recupera a categoria da subcategoria do atributo
        $categoria = $atributo->subcategoria->categoria;

        //Recupera as subcategorias da categoria
        $subcategorias = $categoria->subcategorias;
        return view('dashboard.atributo.atributo-update', ['atributo' => $atributo, 'categorias' => $categorias,    'subcategorias' => $subcategorias, 'tiposAtributo' => $tipos]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Atributo $atributo)
    {
        //Verifica se os valores dos campos, se preenchidos, são válidos
        $validated = $request->validate([
            'subcategoria' => 'required|integer|exists:App\Subcategoria,id',
            'nome' => [
                'required',
                'regex:/^[A-Za-záàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ ]+$/',
                'max:60',
            ],
            'tipoAtr' => 'required|integer|exists:App\TipoAtributo,id',   
        ]);
        //VERIFICANDO SE O ATRIBUTO JÁ EXISTE PARA A SUBCATEGORIA DADA
        if(Atributo::where('subcategorias_id', $validated['subcategoria'])->where('nome', $request->nome)->where('id', "!=", $atributo->id)->exists()) {
            return redirect()->back()->withErrors(['nome' => "O atributo dado já existe para a subcategoria selecionada"]);
        }

        // Se a subcategoria ou tipo do atributo mudar, os produtos configuráveis são deletados e os produtos simples tem o atributo desvinculado.
        if($atributo->subcategorias_id != $validated['subcategoria'] || $atributo->tipos_atributos_id != $validated['tipoAtr']) {
            if($atributo->is_configurable == 1) {
                $this->delete_configurable_products($atributo);
            } else {
                $atributo->produtos()->detach();
            }
        }
        //Se o tipo selecionado for diferente do tipo cadastrado, os valores pré-definidos do atributo são deletados.
        if($atributo->tipos_atributos_id != $validated['tipoAtr']) {
            if($validated['tipoAtr'] == 3 && $atributo->is_configurable == 1) {
                $atributo->is_configurable == 0;
            }
            ValorAtributo::where('atributos_id', $atributo->id)->delete();
        }
        $atributo->nome = $validated['nome'];
        $replaced = Str::snake($validated['nome']);
        $atributo->label = $replaced;
        $atributo->subcategorias_id = $validated['subcategoria'];
        $atributo->tipos_atributos_id =  $validated['tipoAtr'];
        $atributo->is_visible = $request->has('is_visible') ? 1 : 0;
        $atributo->is_required = $request->has('is_required') ? 1 : 0;
        $atributo->save();

        //Redireciona a página de cadastro dos atributos
        return redirect()->route('atributo.show', [$atributo->id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Atributo $atributo)
    {
        if($atributo->is_configurable == 1) {
            $this->delete_configurable_products($atributo);
        } 
        $atributo->delete();
        return redirect()->route('atributo.index');
    }
    public function getAtributos(Request $request) {
        $atributos = DB::table('atributos')
            ->join('subcategorias', 'subcategorias.id', '=', 'atributos.subcategorias_id')
            ->join('tipos_atributos', 'tipos_atributos.id', '=', 'atributos.tipos_atributos_id')
            ->select('atributos.*', 'subcategorias.nome as subcategoria', 'tipos_atributos.frontend_type_label as tipo')
            ->get();
        return response()->json([
            'atributos' => $atributos
        ]);
    }
    public function setConfig(Request $request, $idAtr) {
        $atributo = Atributo::findOrFail($idAtr);
        $config = $request->get('config_name');
        $is_checked = $request->get('is_checked');
        $atributo->$config = $is_checked == "true" ? 1 : 0;
        $atributo->save();
    }

    public function delete_configurable_products($atributo) {
        $produtos = $atributo->produtos()->whereNotNull('produtos.produtos_id')->get();
        $configurableProducts = collect([]);
        foreach($produtos as $prod) {
            $parente = $prod->parente;
            if(!$configurableProducts->contains($parente)) {
                $configurableProducts->push($parente);
            }
        }
        foreach($configurableProducts as $prod) {
            foreach($prod->fotosProduto as $fto) {
                Storage::delete($fto->caminho);
            }
            $prod->delete();
        }
    }
}

app/Http/Controllers/Dashboard/ValorAtributoController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\ValorAtributo;


class ValorAtributoController extends Controller
{
   

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $atributo)
    {
        $valor = new ValorAtributo();
        $valor->atributos_id =  $atributo;
        $valor->valor = $request->get('valor');
        $valor->label = $request->get('label');
        $valor->save();

        return response()->json([
            'valor' => $valor->valor,
            'label' => $valor->label,
            'id' => $valor->id,
        ]);

    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $valor = ValorAtributo::findOrFail($id);
        $valor->delete();
        
        return response()->json([
            'id' => $valor->atributo->id,
            'is_configurable' =>  $valor->atributo->is_configurable,
        ]);
    }
}

resources/views/dashboard/atributo/atributo-create.blade.php
    @extends('layouts.dashboard')

    @section('title', 'Atributos')

    @section('icon')
        <i class="fas fa-tint"></i>
    @endsection

    @section('desc', 'Cadastre, atualize ou remova os atributos das subcategorias de produtos ofertados na loja.')

    @section('content')
    
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb px-0 bg-transparent">
            <li class="breadcrumb-item"><a href="{{ route('atributo.index') }}">Atributos</a></li>
                <li class="breadcrumb-item active" aria-current="page">Cadastrar</li>
            </ol>
        </nav>
        
        <div class="row justify-content-center my-5">
            @if(isset($categorias))
                <!--Cadastro dos atributos-->
                <div class="col-lg-10 col-xl-9">
                    <div class="card content-card">
                        <h1 class="h5 mb-4">
                            Novo atributo
                        </h1>
                        <form method="POST" action="{{ route('atributo.store') }}" id="cadAtr">
                            @csrf
                            <div id="carousel" class="carousel" data-ride="carousel" data-interval="false">
                                <div class="carousel-inner">
                                    @if($errors->any())
                                        <div class="alert alert-danger">
                                            Alguns campos são inválidos. Por favor, tente novamente!
                                        </div>
                                    @endif
                                    <x-choose-categorie :categorias="$categorias"></x-choose-categorie>
                                    <!--Nome e tipo de dados-->
                                    <div class="carousel-item">
                                        <x-card card-title="Dados do atributo">
                                            <x-slot name="card_body">
                                                <!--Campos-->
                                                <div class="form-row">
                                                    <!--Nome do atributo-->
                                                    <div class="form-group col-md-6" id="nameGroup">
                                                        <label for="nome">Nome</label>
                                                        <input 
                                                        type="text" 
                                                        class="form-control @error('nome') is-invalid @enderror mb-2" 
                                                        name="nome" 
                                                        id="nome" 
                                                        required 
                                                        maxlength="60" />
                                                        <span class="invalid-feedback" id="info_nome">
                                                            <strong>
                                                                @error('nome')
                                                                    {{$message}}
                                                                @enderror
                                                            </strong>
                                                        </span>
                                                    </div>

                                                    <!--Tipo de dados-->
                                                    <div class="form-group col-md-6">
                                                        <div class="form-row">
                                                            <div class="col-auto">
                                                                <label for="tipoAtr">
                                                                    Tipo de dados  
                                                                </label>
                                                            </div>
                                                            <div class="col-auto">
                                                                <a tabindex="0" class="pop-button" role="button" data-toggle="popover" data-trigger="focus" data-placement="top" data-content="O tipo do atributo determina os valores aceitos no momento de cadastro dos produtos." title="Tipo de dados">
                                                                    <i class="fas fa-question-circle text-info"></i>
                                                                </a>
                                                            </div>
                                                        </div>
                                                    
                                                        <select class="form-control" name="tipoAtr" id="tipoAtr">
                                                            @foreach($tiposAtributos as $tipo)
                                                                <option value="{{ $tipo->id }}">{{ $tipo->frontend_type_label }}</option> 
                                                            @endforeach
                                                        </select>
                                                    </div>

                                                    <div class="col">
                                                        <!--É visível-->
                                                        <div class="form-group">
                                                            <div class="custom-control custom-switch mb-1">
                                                                <input 
                                                                type="checkbox" 
                                                                class="custom-control-input" 
                                                                name="is_visible" 
                                                                id="is_visible"
                                                                checked/>
                                                                <label class="custom-control-label" for="is_visible">Visível</label>
                                                            </div>
                                                            <p class="text-gray-600 small">O atributo será exibido no momento de cadastro dos produtos.</p>
                                                        </div>
                                                        <!--É obrigatório-->
                                                        <div class="form-group">
                                                            <div class="custom-control custom-switch mb-1">
                                                                <input 
                                                                type="checkbox" 
                                                                class="custom-control-input" 
                                                                name="is_required" 
                                                                id="is_required"
                                                                checked/>
                                                                <label class="custom-control-label" for="is_required">Obrigatório</label>
                                                            </div>
                                                            <p class="text-gray-600 small">Será necessário selecionar ou definir um valor para o atributo no cadastro dos produtos.</p>
                                                        </div>
                                                        <!--É configurável-->
                                                        <div class="form-group d-none" id="atrIsConfig">
                                                            <div class="custom-control custom-switch mb-1">
                                                                <input 
                                                                type="checkbox" 
                                                                class="custom-control-input" 
                                                                name="is_configurable" 
                                                                id="is_configurable"/>
                                                                <label class="custom-control-label" for="is_configurable">Configurável</label>
                                                            </div>
                                                            <p class="text-gray-600 small">Voce poderá selecionar ou definir mais de um valor para o atributo, criando variações do produto.</p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </x-slot>
                                            <x-slot name="card_footer">
                                                <button type="button" onclick="checkGroupValidity('nameGroup', 'submit', 'cadAtr')" class="btn btn-success float-right" >Finalizar</button>
                                            </x-slot>
                                        </x-card>
                                    </div>
                                </div>
        
                                <!--Controles-->
                                <a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev">
                                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                    <span class="sr-only">Previous</span>
                                </a>
                            </div>
                        </form>
                    </div>
                </div>
            @endif
        </div>
    @endsection
    
    @section('pl-custom-scripts')
        <!-- Page level custom scripts -->
        <script src="{{ asset('js/custom/dashboard/create.js') }}"></script>
        
        <script>
            $(document).ready(function () { 
                showConfigurable($('#tipoAtr').val());
            })

            //Verifica se o tipo do atributo é lógico e esconde o campo "Configurável"
            function showConfigurable(val) {
                if(val == "3") {
                    $('#atrIsConfig').addClass('d-none');
                    $('#atrIsConfig').prop('checked', false)
                } else {
                    $('#atrIsConfig').removeClass('d-none');
                }
            }
            $('#tipoAtr').change(function(){
                showConfigurable(this.value);
            })            
            function getSubcategorias(id) {
                $.ajax({
                    url: '{{ route("categoria.getSubcategorias")}}',
                    method: 'GET',
                    datatype: "JSON",
                    data: {
                        categoria: id,
                    },
                    beforeSend: function() {
                        $('#carousel').addClass('carousel-sliding');
                    },
                    success: function(response) {
                        var subcategorias = response.subcategorias;
                        $('#subcatList .list-group-item').remove();

                        //Carrega as subcategorias
                        for(var i = 0; i < subcategorias.length; i++) {
                            let option = `
                                <li 
                                onclick="loadLiValue(this, null)"
                                class="list-group-item"
                                data-submit="next"
                                data-parent="subcatList"
                                data-option-value="subcatInput/${subcategorias[i].id}">
                                    <span>${subcategorias[i].nome}</span>
                                    <i class="fas fa-long-arrow-alt-right"></i>
                                </li>
                            `;
                            $('#subcatList').append(option);
                        }
                        $('#carousel').carousel('next');
                    },
                    error: function(xhr, status, code) {
                        console.log(xhr);
                    },
                    complete: function() {
                        $('#carousel').removeClass('carousel-sliding');
                    }
                })
            }
        </script>
    @endsection