routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/', 'Shop\HomeController@index')->name('shop.home');



//ROTAS DO PAINEL DE CONTROLE (DASHBOARD)
Route::middleware(['auth', 'checkUserRole'])->group(function () {
        Route::get('dashboard/categoria/get', 'Dashboard\CategoriaController@getCategorias')->name('getCategorias');

        Route::get('dashboard/categoria/subcategorias', 'Dashboard\CategoriaController@getSubcategorias')->name('categoria.getSubcategorias');

        Route::resource('dashboard/categoria', 'Dashboard\CategoriaController')
        ->parameters([
                'categoria' => 'categoria',
        ])
        ->except('create', 'edit', 'show');


        Route::put('dashboard/subcategoria/{subcategoria}/categoria', 'Dashboard\SubcategoriaController@updateParent')->name('subcategoria.updateParent');

        Route::resource('dashboard/subcategoria', 'Dashboard\SubcategoriaController')
        ->parameters([
                'subcategoria' => 'subcategoria',
        ])
        ->only('store', 'destroy', 'update');
        

                
        //Rotas de atributos 
        Route::get('dashboard/atributos/get', 'Dashboard\AtributoController@getAtributos')->name('getAttributes');
        Route::resource('dashboard/atributo', 'Dashboard\AtributoController');

        Route::resource('dashboard/atributo.valores', 'Dashboard\ValorAtributoController')
                ->only('store', 'destroy')
                ->shallow();


        

        Route::PUT('dashboard/atributo/{atributo}/config', 'Dashboard\AtributoController@setConfig');

        

        //ATRIBUTOS DAS CONFIGURAÇÕES
        Route::POST('dashboard/produto/variation', 'Dashboard\ProdutoController@setVariation')->name('produto.setVariation');
        
        Route::POST('dashboard/produto/variation/generalAttribute', 'Dashboard\ProdutoController@setVariationsGeneralAttribute')->name('produto.setVariationsGeneralAttribute');

        Route::DELETE('dashboard/produto/variation', 'Dashboard\ProdutoController@destroyVariation')->name('produto.destroyVariation');

        // ATRIBUTOS DO PRODUTO
        Route::POST('dashboard/produto/generalAtribute', 'Dashboard\ProdutoController@setGeneralAttribute')->name('produto.setGeneralAttribute');
        
        Route::POST('dashboard/produto/simpleAttribute', 'Dashboard\ProdutoController@setSimpleAttribute')->name('produto.setSimpleAttribute');

        Route::PUT('dashboard/produto/multipleGeneralAttributes', 'Dashboard\ProdutoController@updateMultipleGeneralAttributes')->name('produto.updateMultipleGeneralAttributes');

        Route::PUT('dashboard/produto/{produto}/generalAttribute', 'Dashboard\ProdutoController@updateGeneralAttribute')->name('produto.updateGeneralAttribute');


        // FOTOS DO PRODUTO
        Route::POST('dashboard/produto/photos', 'Dashboard\ProdutoController@setPhotos')->name('produto.setPhotos');

        Route::POST('dashboard/produto/{produto}/photos/database', 'Dashboard\ProdutoController@setPhotosToDatabase')->name('produto.setPhotosToDatabase');

        Route::DELETE('dashboard/produto/photos', 'Dashboard\ProdutoController@destroyPhoto')->name('produto.destroyPhoto');
        
        Route::DELETE('dashboard/produto/photos/database', 'Dashboard\ProdutoController@destroyPhotoFromDatabase')->name('produto.destroyPhotoFromDatabase');


        // FOTO PRINCIPAL
        Route::POST('dashboard/produto/photos/main', 'Dashboard\ProdutoController@setMainPhoto')->name('produto.setMainPhoto');

        Route::PUT('dashboard/produto/{produto}/photos/main', 'Dashboard\ProdutoController@updateMainPhoto')->name('produto.updateMainPhoto');


       
        //CRUD Produtos
        Route::resource('dashboard/produto', 'Dashboard\ProdutoController')->except('edit');

});

//ROTAS DO SHOP
Route::get('shop/catalogo', 'Shop\ShopController')->name('shop.catalogo');

Route::get('shop/categorias', 'Shop\ShowCategorias')->name('shop.categorias');

Route::get('shop/produto/unavaliable', 'Shop\ShowProduto@unavaliable')->name('shop.produto.unavaliable');

Route::get('shop/produto/{produto}', 'Shop\ShowProduto@show')->name('shop.produto')->middleware('checkProductStatus');

Route::get('shop/produto/{produto}/avaliacoes', 'User\AvalController@index')->name('shop.produtos.avaliacoes');

Route::get('shop/produto/{produto}/variation', 'Dashboard\ProdutoController@getVariation')->name('produto.getVariation');


//ROTAS PERFIL DO USUÁRIO
Route::middleware(['auth'])->group(function () {
        //ROTAS PERFIL DE USUÁRIO
        Route::get('user/profile', 'UserController@show')->name('user.profile');

        Route::put('user/profile', 'UserController@update')->name('user.profile.update');

        Route::get('user/profile/edit', 'UserController@edit')->name('user.profile.edit');

        Route::resource('user/address', 'User\EnderecoUsuarioController')->except('show', 'index');

        Route::put('user/address/{address}/setMain', 'User\EnderecoUsuarioController@setMain')->name('address.setMain');

        Route::get('password/edit', 'UserController@editPassword')->middleware('password.confirm')->name('password.edit');

        Route::put('password', 'UserController@changePassword')->name('password.change');

        //ROTAS SACOLA DE PRODUTOS
        Route::get('user/bag', 'User\BagController@show')->name('user.bag')->middleware('checkUserBag');

        Route::get('user/bag/empty', 'User\BagController@empty')->name('user.bag.empty');

        Route::post('user/bag/produto', 'User\BagController@addProductToBag')->name('bag.produto.store');

        Route::delete('user/bag/produto/{produto}', 'User\BagController@removeProductFromBag')->name('bag.produto.delete');

        Route::put('user/bag/produto/{produto}/quantity', 'User\BagController@updateProductBagQuantity')->name('bag.produto.quantity');
        
        Route::post("user/bag/address", 'User\EnderecoUsuarioController@store')->name('bag.address.store');

        Route::put('user/bag/address/{address}', 'User\BagController@updateBagAddress')->name('bag.address.update');


        // ROTAS FAVORITOS
        Route::get('user/favorites', 'User\FavoritesController@index')->name('user.favorites');

        Route::POST('user/favorites/produto/{produto}', 'User\FavoritesController@addProductToFavorites')->name('favorites.produto.store');
        
        Route::DELETE('user/favorites/produto/{produto}', 'User\FavoritesController@removeProductFromFavorites')->name('favorites.produto.delete');


        // ROTAS DE PEDIDOS
        Route::get('user/orders', 'User\OrdersController@index')->name('user.orders');

        Route::get('user/orders/{order}', 'User\OrdersController@show')->name('user.orders.show');

        Route::put('shop/checkout/finish/shipping', 'Shop\Checkout@loadShippingValue')->name('shop.checkout.shipping');

        // ROTAS DE AVALIACOES
        Route::resource('user/orders.produto.avaliacao', 'User\AvalController')->except('index', 'show');

});

//ROTAS DE CHECKOUT
Route::middleware(['auth', 'checkProductsInBagStatus'])->group(function () {
        Route::get('shop/checkout/address', 'Shop\Checkout@address')->name('shop.checkout.address');

        Route::get('shop/checkout/personal-info', 'Shop\Checkout@personal_info')->name('shop.checkout.personal-info');

        Route::get('shop/checkout/finish', 'Shop\Checkout@finish')->middleware('checkUserInfo')->name('shop.checkout');

        Route::post('shop/checkout/finish', 'Shop\Checkout@order')->name('shop.checkout.order');
});

app/Http/Controllers/Dashboard/AtributoController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Categoria;
use App\TipoAtributo;
use App\ValorAtributo;
use App\Atributo;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class AtributoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('dashboard.atributo.atributo-index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //Recupera as categorias de produtos
        $categorias = Categoria::withCount('subcategorias')->get();
        
        //Recupera os tipos de atributos
        $tiposAtributos = TipoAtributo::all();
        return view('dashboard.atributo.atributo-create', ['categorias' => $categorias, 'tiposAtributos' => $tiposAtributos]);
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
   

    public function store(Request $request) {
        //Verifica se os valores dos campos, se preenchidos, são válidos
        $validated = $request->validate([
            'subcategoria' => 'required|integer|exists:App\Subcategoria,id',
            'nome' => [
                'required',
                'regex:/^[A-Za-záàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ ]+$/',
                'max:60',
            ],
            'tipoAtr' => 'required|integer|exists:App\TipoAtributo,id',   
            'is_configurable' => 'exclude_if:tipoAtr,3',
        ]);
        // VERIFICA SE O ATRIBUTO JÁ FOI CADASTRADO PARA A SUBCATEGORIA SELECIONADA
        if(Atributo::where('subcategorias_id', $validated['subcategoria'])->where('nome', $validated['nome'])->exists()) {
            return redirect()->back()->withErrors(['nome' => "O atributo dado já existe para a subcategoria selecionada"]);
        }

        //Gera uma instancia do atributo e define os valores das propriedades
        $atributo = new Atributo();
        $atributo->subcategorias_id = $validated['subcategoria'];
        $atributo->nome = $validated['nome'];
        $replaced = Str::snake($validated['nome']);
        $atributo->label = $replaced;
        $atributo->tipos_atributos_id =  $validated['tipoAtr'];
        $atributo->is_visible = $request->has('is_visible') ? 1 : 0;
        $atributo->is_required = $request->has('is_required') ? 1 : 0;
        $atributo->is_configurable = isset($validated['is_configurable']) ? 1 : 0;
        $atributo->save();

        //Redireciona a página de cadastro dos atributos
        return redirect()->route('atributo.show', [$atributo->id]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Atributo $atributo) {
        return view('dashboard.atributo.atributo-show', ['atributo' => $atributo]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Atributo $atributo)
    {
        $categorias = Categoria::withCount('subcategorias')->get();
        $tipos = TipoAtributo::all();

        //Recupera a categoria da subcategoria do atributo
        $categoria = $atributo->subcategoria->categoria;

        //Recupera as subcategorias da categoria
        $subcategorias = $categoria->subcategorias;
        return view('dashboard.atributo.atributo-update', ['atributo' => $atributo, 'categorias' => $categorias,    'subcategorias' => $subcategorias, 'tiposAtributo' => $tipos]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Atributo $atributo)
    {
        //Verifica se os valores dos campos, se preenchidos, são válidos
        $validated = $request->validate([
            'subcategoria' => 'required|integer|exists:App\Subcategoria,id',
            'nome' => [
                'required',
                'regex:/^[A-Za-záàâãéèêíïóôõöúçñÁÀÂÃÉÈÍÏÓÔÕÖÚÇÑ ]+$/',
                'max:60',
            ],
            'tipoAtr' => 'required|integer|exists:App\TipoAtributo,id',   
        ]);
        //VERIFICANDO SE O ATRIBUTO JÁ EXISTE PARA A SUBCATEGORIA DADA
        if(Atributo::where('subcategorias_id', $validated['subcategoria'])->where('nome', $request->nome)->where('id', "!=", $atributo->id)->exists()) {
            return redirect()->back()->withErrors(['nome' => "O atributo dado já existe para a subcategoria selecionada"]);
        }

        // Se a subcategoria ou tipo do atributo mudar, os produtos configuráveis são deletados e os produtos simples tem o atributo desvinculado.
        if($atributo->subcategorias_id != $validated['subcategoria'] || $atributo->tipos_atributos_id != $validated['tipoAtr']) {
            if($atributo->is_configurable == 1) {
                $this->delete_configurable_products($atributo);
            } else {
                $atributo->produtos()->detach();
            }
        }
        //Se o tipo selecionado for diferente do tipo cadastrado, os valores pré-definidos do atributo são deletados.
        if($atributo->tipos_atributos_id != $validated['tipoAtr']) {
            if($validated['tipoAtr'] == 3 && $atributo->is_configurable == 1) {
                $atributo->is_configurable == 0;
            }
            ValorAtributo::where('atributos_id', $atributo->id)->delete();
        }
        $atributo->nome = $validated['nome'];
        $replaced = Str::snake($validated['nome']);
        $atributo->label = $replaced;
        $atributo->subcategorias_id = $validated['subcategoria'];
        $atributo->tipos_atributos_id =  $validated['tipoAtr'];
        $atributo->is_visible = $request->has('is_visible') ? 1 : 0;
        $atributo->is_required = $request->has('is_required') ? 1 : 0;
        $atributo->save();

        //Redireciona a página de cadastro dos atributos
        return redirect()->route('atributo.show', [$atributo->id]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Atributo $atributo)
    {
        if($atributo->is_configurable == 1) {
            $this->delete_configurable_products($atributo);
        } 
        $atributo->delete();
        return redirect()->route('atributo.index');
    }
    public function getAtributos(Request $request) {
        $atributos = DB::table('atributos')
            ->join('subcategorias', 'subcategorias.id', '=', 'atributos.subcategorias_id')
            ->join('tipos_atributos', 'tipos_atributos.id', '=', 'atributos.tipos_atributos_id')
            ->select('atributos.*', 'subcategorias.nome as subcategoria', 'tipos_atributos.frontend_type_label as tipo')
            ->get();
        return response()->json([
            'atributos' => $atributos
        ]);
    }
    public function setConfig(Request $request, $idAtr) {
        $atributo = Atributo::findOrFail($idAtr);
        $config = $request->get('config_name');
        $is_checked = $request->get('is_checked');
        $atributo->$config = $is_checked == "true" ? 1 : 0;
        $atributo->save();
    }

    public function delete_configurable_products($atributo) {
        $produtos = $atributo->produtos()->whereNotNull('produtos.produtos_id')->get();
        $configurableProducts = collect([]);
        foreach($produtos as $prod) {
            $parente = $prod->parente;
            if(!$configurableProducts->contains($parente)) {
                $configurableProducts->push($parente);
            }
        }
        foreach($configurableProducts as $prod) {
            foreach($prod->fotosProduto as $fto) {
                Storage::delete($fto->caminho);
            }
            $prod->delete();
        }
    }
}

app/Http/Controllers/Dashboard/ValorAtributoController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\ValorAtributo;


class ValorAtributoController extends Controller
{
   

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $atributo)
    {
        $valor = new ValorAtributo();
        $valor->atributos_id =  $atributo;
        $valor->valor = $request->get('valor');
        $valor->label = $request->get('label');
        $valor->save();

        return response()->json([
            'valor' => $valor->valor,
            'label' => $valor->label,
            'id' => $valor->id,
        ]);

    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $valor = ValorAtributo::findOrFail($id);
        $valor->delete();
        
        return response()->json([
            'id' => $valor->atributo->id,
            'is_configurable' =>  $valor->atributo->is_configurable,
        ]);
    }
}

resources/views/dashboard/produto/produto-index.blade.php
@extends('layouts.dashboard')

@section('title', 'Produtos')

@section('pl-custom-styles')
    <!-- Custom styles for this page -->
    <link href="{{ asset('css/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
@endsection


@section('icon')
    <i class="fas fa-mobile-alt"></i>
@endsection

@section('desc', 'Cadastre, atualize ou remova os produtos ofertados na loja.')

@section('content')
    <div class="row my-4 justify-content-center my-5">
        <div class="col-lg-10 mb-5">
            <div class="card content-card">
                <div class="flex-between mb-5">
                    <div>
                        <h2 class="h5 mb-0">Produtos cadastrados</h2>
                        <p class="mb-0">Use o campo de busca para pesquisar por um nome, SKU ou outro valor</p>
                    </div>
                    <a href="{{ route('produto.create') }}" class="btn btn-primary float-right"><i class="fas fa-plus mr-2"></i>Novo</a>
                </div>
                <div class="table-responsive">
                    <table class="table " id="productDataTable">
                        <thead>
                            <tr>
                                <th></th>
                                <th>Nome</th>
                                <th>SKU</th>
                                <th>Subcategoria</th>
                                <th>Visível</th>
                                <th class="small">Estoque</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($produtos as $prod)
                                <tr>
                                    <td>
                                        <div class="listable-product-image img-xs thumb">
                                            <img src="{{ asset('storage/' . $prod->fotosProduto()->where('is_main', 1)->first()->caminho) }}" alt="" class="img-fluid">
                                        </div>
                                    </td>
                                    <td><a href="{{ route('produto.show', [$prod->id]) }}">{{ $prod->nome }}</a></td>
                                    <td>
                                        @if($prod->filhos()->exists())
                                            @foreacH($prod->filhos as $filho)
                                                {{$filho->sku}}<br>
                                            @endforeach
                                        @else 
                                            {{ $prod->sku }}
                                        @endif
                                    </td>
                                    <td>{{ $prod->subcategoria->nome }}</td>
                                    <td>
                                        @if($prod->is_visible) Sim @else Não @endif
                                    </td>
                                    <td>
                                        @if($prod->is_avaliable) 
                                            <span class="badge badge-success">Disponível</span> 
                                        @else 
                                            <span class="badge badge-danger">Indisponível</span> 
                                        @endif
                                    </td>
                                    <td>
                                        <button type="button" class="btn btn-action"  data-toggle="modal" data-target="#modalDelete" data-id="{{$prod->id}}">
                                            <i class="fas fa-trash-alt"></i>
                                        </button>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                        <tfoot>
                            <tr>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                                <th></th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div> 

    <div class="modal fade" id="modalDelete" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content py-4">
                <div class="modal-body">
                    <div class="row justify-content-center">
                        <div class="col-auto mb-3 modal-icon bg-white shadow-sm">
                            <i class="fas fa-exclamation-circle text-reddish"></i>
                        </div>
                        <div class="w-100"></div>
                        <div class="col-sm-10 mb-4 text-justify">
                            <h3 class="h4 mb-4 text-gray-800 text-center">Atenção</h3>
                            <p>Ao deletar esse produto, ele não será mais listado no painel de controle ou catálogo da loja, mas ainda poderá ser visto nos pedidos dos usuários. Deseja continuar?</p>
                        </div>
                        <div class="w-100"></div>
                        <div class="col">
                            <div class="row justify-content-center">
                                <div class="col-4">
                                    <button type="button" class="btn btn-block btn-lg btn-secondary" data-dismiss="modal">Cancelar</button>
                                </div>
                                <div class="col-4">
                                <form method="POST" id="formDelete" action="{{ route('produto.destroy', [0]) }}">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-block btn-lg btn-danger">Excluir</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection


@section('pl-plugins')
    <!--Plugins-->
    <script src="{{ asset('js/dependencies/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('js/dependencies/dataTables.bootstrap4.min.js') }}"></script>
@endsection

@section('pl-custom-scripts')
    <script src="{{ asset('js/custom/dashboard/index.js') }}"></script>
    <script>
        
        $(document).ready(function() { 
            //Carrega a datatables
            var table = $('#productDataTable').DataTable({
                order: [1, 'asc'],
                columns: [
                    {"orderable": false, },
                    { "className": 'small'},
                    {"className": "text-nowrap small"},
                    { "className": 'small'},
                    { "className": 'small'},
                    {},
                    {
                        "className": 'text-center small',
                        "orderable":      false,
                    },
                ],
                initComplete: function () {
                    this.api().columns([3]).every( function () {
                        var column = this;
                        var select = $('<select class="form-control"><option value=""></option></select>')
                            .appendTo( $(column.footer()).empty() )
                            .on( 'change', function () {
                                var val = $.fn.dataTable.util.escapeRegex(
                                    $(this).val()
                                );
        
                                column
                                    .search( val ? '^'+val+'$' : '', true, false )
                                    .draw();
                            } );
        
                        column.data().unique().sort().each( function ( d, j ) {
                            select.append( '<option value="'+d+'">'+d+'</option>' )
                        } );
                    } );
                },
            });
        });
    </script>
@endsection